### ISSUE TITLE
Thousands of "Skipping cache lookup" messages

### ISSUE THREAD

**Issue by alexisph** [konveyor/oadp-operator#102]
Hi.

We've deployed OADP operator on OCP v4.6 via this procedure: https://github.com/konveyor/oadp-operator#getting-started-with-basic-install-non---olm

We have observed an immense amount of logs being emitted by the oadp-operator pod:

![image](https://user-images.githubusercontent.com/1152793/117623017-f259d780-b17b-11eb-8ca5-330a51f13a15.png)
  
```
  ...
{"level":"info","ts":1620604499.8003464,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/apis","Verb":"get","APIPrefix":"","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
...
--------------------------- Ansible Task StdOut -------------------------------
...
TASK [velero : Set up velero controller] ***************************************
...
```

and so on.

The result is that our Cluster Logging Elasticsearch instance is being filled completely in 2-3 days.

How do we disable this excessive logging? I have found that the ansible-operator base image used by the oadp-opearator is still on [v0.17.0](https://github.com/operator-framework/operator-sdk/releases/tag/v0.17.0). There was a [fix](https://github.com/operator-framework/operator-sdk/pull/4511) that was released a few months ago and is not included in that version. It is included in [v1.5.0](https://github.com/operator-framework/operator-sdk/releases/tag/v1.5.0) and later.

Refs:
https://github.com/openshift/openshift-restclient-python/issues/384
https://github.com/operator-framework/operator-sdk/pull/3933
https://stackoverflow.com/questions/67415884/how-to-reduce-the-log-verbosity-of-ansible-based-kubernetes-operator-deployment
https://github.com/operator-framework/operator-sdk/issues/4519
https://github.com/operator-framework/operator-sdk/pull/4511

**Edit:**
We built the oadp-operator using the ansible-operator:v1.5.0 as base image and the excessive logging has stopped.

**Comment by dymurray** [comment]
Thank you for reporting this. Sounds like upgrading to a newer ansible-operator base image will help us here.
