### ISSUE TITLE
Copy OADP backups to other storage and store them independently

### ISSUE THREAD

**Issue by mapo4** [konveyor/oadp-operator#104]
Hi, 

I found that restic application supports data backup in OADP. What if I want to make copy of this backed-up data to other storage, I need to use restic mechanism for that? Is OADP has internal mechanism to copy backed-up data to other place/storage? Simply I want to store those backups independently in other storage.

**Comment by dymurray** [comment]
Scott is correct. Also, it sounds like you are interested in a "data mover", i.e. the ability to move your persistent storage data backups to external locations and have the ability to restore from that external location. This is something that is in development for OADP.
