### ISSUE TITLE
Specify nodeSelector for restic DaemonSet

### ISSUE THREAD

**Issue by brandonwilliamsised** [konveyor/oadp-operator#112]
Hi there,

Is it possible to specify a nodeSelector for the Restic DS to use, similar to mig-operator (https://github.com/konveyor/mig-operator/blob/master/roles/migrationcontroller/templates/velero.yml.j2#L190)

On an OpenShift 4.7 cluster with dedicated infrastructure nodes (OpenShift Container Storage), the restic DS fails to fully roll out as it attempts to install on all non-master nodes.

**Comment by dymurray** [comment]
This should be a simple change. Adding as a GA blocker. Any restic/velero customization that MTC supports OADP should support.
