### ISSUE TITLE
Support for Openshift 3.11?

### ISSUE THREAD

**Issue by sbuvaneshkumar** [konveyor/oadp-operator#51]
Can we document in README file if this is supported in openshift 3.11?

**Comment by dymurray** [comment]
@sbuvaneshkumar I will add some notes on supported versions, but yes this is supported for OCP 3.11.

**Comment by gojeaqui** [comment]
I am unable to deploy the operator on OCP 3.11

In the following step:
`[root@xocpinstaller oadp-operator]# oc create -f deploy/crds/konveyor.openshift.io_veleros_crd.yaml`

This is the error:
`The CustomResourceDefinition "veleros.konveyor.openshift.io" is invalid: spec.validation.openAPIV3Schema: Invalid value: apiextensions.JSONSchemaProps{ID:"", Schema:"", Ref:(*string)(nil), Description:"", Type:"object", Format:"", Title:"", Default:(*apiextensions.JSON)(nil), Maximum:(*float64)(nil), ExclusiveMaximum:false, Minimum:(*float64)(nil), ExclusiveMinimum:false, MaxLength:(*int64)(nil), MinLength:(*int64)(nil), Pattern:"", MaxItems:(*int64)(nil), MinItems:(*int64)(nil), UniqueItems:false, MultipleOf:(*float64)(nil), Enum:[]apiextensions.JSON(nil), MaxProperties:(*int64)(nil), MinProperties:(*int64)(nil), Required:[]string(nil), Items:(*apiextensions.JSONSchemaPropsOrArray)(nil), AllOf:[]apiextensions.JSONSchemaProps(nil), OneOf:[]apiextensions.JSONSchemaProps(nil), AnyOf:[]apiextensions.JSONSchemaProps(nil), Not:(*apiextensions.JSONSchemaProps)(nil), Properties:map[string]apiextensions.JSONSchemaProps(nil), AdditionalProperties:(*apiextensions.JSONSchemaPropsOrBool)(nil), PatternProperties:map[string]apiextensions.JSONSchemaProps(nil), Dependencies:apiextensions.JSONSchemaDependencies(nil), AdditionalItems:(*apiextensions.JSONSchemaPropsOrBool)(nil), Definitions:apiextensions.JSONSchemaDefinitions(nil), ExternalDocs:(*apiextensions.ExternalDocumentation)(nil), Example:(*apiextensions.JSON)(nil)}: must only have "properties", "required" or "description" at the root if the status subresource is enabled
`

**Comment by gojeaqui** [comment]
The problem might be that I already have velero CRDs installed by MTC, the problem is that I am unable to use the velero that comes with MTC in a standalone manner ([Backups fail when using plugin outside of OADP/CAM context #59](https://github.com/konveyor/openshift-velero-plugin/issues/59))

**Comment by dymurray** [comment]
With the CRD updates to Velero this will no longer work on OCP 3.11.
