### ISSUE TITLE
Missing LD_LIBRARY_PATH in Velero pod deployed by OADP operator

### ISSUE THREAD

**Issue by phuongatemc** [konveyor/oadp-operator#64]
Velero's LB_LIBRARY_PATH is set to "/plugins" directory so if any plugin binary needs to load additional library during execution, it can put the library there.  However, Velero installed by OADP missing this environment variable and therefore fail the plugins that needs to load libraries even though the library binaries are there in the /plugins directory.

Reproduce steps:
- install OADP operator
- create simple Velero with default csi, openshift plugins (see config below)
apiVersion: konveyor.openshift.io/v1alpha1
kind: Velero
metadata:
  name: example-velero
  namespace: oadp-operator
spec:
  olm_managed: true
  use_upstream_images: true
  default_velero_plugins:
    - csi
    - openshift
  enable_restic: true
  
 then use "exec -it " to log into Velero pod and print out all evn

#oc get pod velero-7d9cd8489b-7v5cx -n oadp-operator bash
#env | grep LD_LIBRARY_PATH 
==> found nothing

**Comment by dymurray** [comment]
@phuongatemc Thank you for reporting this. This should be a fairly easy fix. Will set `LD_LIBRARY_PATH` to `/plugins` in our velero deployment

**Comment by dymurray** [comment]
@phuongatemc once above PR is merged just delete the oadp-operator pod and the `velero` deployment. This should force it to be recreated with the right env vars.
