### ISSUE TITLE
Failing to create a Velero instance

### ISSUE THREAD

**Issue by susinths** [konveyor/oadp-operator#78]
Redhat OCP 4.6 and using OADP operator v 0.2.0. Installation of operator is successfull, but trying to create a Velero instance using AWS cloud provider fails with:
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'cloud'

The error appears to be in '/opt/ansible/roles/velero/tasks/main.yml': line 60, column 5, but may
be elsewhere in the file 

The YAML shows the following:

status:
  conditions:
    - ansibleResult:
        changed: 0
        completion: '2021-02-26T15:38:59.792135'
        failures: 1
        ok: 8
        skipped: 42
      lastTransitionTime: '2021-02-26T15:39:00Z'
      message: >
        The task includes an option with an undefined variable. The error was:
        'dict object' has no attribute 'cloud'

        The error appears to be in '/opt/ansible/roles/velero/tasks/main.yml':
        line 60, column 5, but may

        be elsewhere in the file depending on the exact syntax problem.

        The offending line appears to be:

          - name: Decode AWS credentials
            ^ here
      reason: Failed

Any help appreciated! :-)

**Comment by sseago** [comment]
@susinths From the error, it looks like the aws secret is missing the credentials, which should be found in `data.cloud`. Was the secret created as described in https://github.com/konveyor/oadp-operator#creating-credentials-secret ?

**Comment by dymurray** [comment]
I agree with Scott. That sounds like what you are missing. We should handle this error more gracefully and display it to the end user but I believe this is just missing that secret with data.
