### ISSUE TITLE
Harcoded container image vars in the operator

### ISSUE THREAD

**Issue by gauthiersiri** [konveyor/oadp-operator#98]
The goal is to perform an airgap install of OADP
- Pull OADP images from quay.io and pushed them to OCP registry
- Deployed the operator "non-olm", customizing registry, project and image version
- Deployed Velero using a CR

Unfortunately some image still try to be pulled from quay.

In the file oadp-operator/roles/velero/defaults/main.yml, for some images, registry and project are harcoded (like quay_registry & konveyor_project vars, but more generally don't use env vars).

This prevents airgap deployment unfortunately.

Temp solution for me was to clone the repo, change the file, rebuild oadp operator image, but it should be change at the source :)

**Comment by jwmatthews** [comment]
@gauthiersiri thank you for filing the issue.  We haven't added support yet for testing installs in a restricted network environment.

**Comment by sabre1041** [comment]
Ran into similar issues and wanted to note hardcoded template values that cannot be overridden by Ansible Variables

* https://github.com/konveyor/oadp-operator/blob/master/roles/velero/templates/noobaa_registry.yml.j2#L19
* https://github.com/konveyor/oadp-operator/blob/master/roles/velero/templates/registry_aws.yml.j2#L21
* https://github.com/konveyor/oadp-operator/blob/master/roles/velero/templates/registry_gcp.yml.j2#L21

**Comment by alexisph** [comment]
Ran across this issue as well. Needed to modify the template files and rebuild the oadp-operator image.

**Comment by dymurray** [comment]
Thanks for this, will get this resolved ASAP.
